title: Robacarp
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://robacarp.io" # the base hostname & protocol for your site
permalink: "/:categories/:year/:month/:day/:title.html"

# Build settings
markdown: kramdown
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
 - bin
 - config.ru
 - Procfile
 - nginx
 - Dockerfile

include:
  - .well-known
