title: Robacarp
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://robacarp.io" # the base hostname & protocol for your site
permalink: "/:categories/:year/:month/:day/:title.html"

author:
  name: Robert Carpenter

# Build settings
markdown: kramdown
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
 - bin
 - config.ru
 - Procfile
 - nginx
 - Dockerfile

include:
  - .well-known

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - month
    - day
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
