version: 0.2

phases:
  install:
    commands:
      - bundle install
  build:
    commands:
      - mkdir _site
      - find .
      - jekyll build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - whoami
      - ls -lah
artifacts:
  files:
    - '**/*'
  base-directory: _site
