version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
jobs:
  deployment:
    docker:
      - image: 'circleci/python:3.7.1'
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_REGION

      - checkout
      - run: ./scripts/build
      - run: ./scripts/upload_image
      - run: ./scripts/deploy_latest

workflows:
  deploy:
    jobs:
      - deployment:
          filters:
            branches:
              only: master
