title: Robacarp
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robacarp.io" # the base hostname & protocol for your site
permalink: "/:year/:month/:day/:title.html"

port: 3999

author:
  name: Robert Carpenter

# Build settings
markdown: kramdown
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
 - scripts
 - config.ru
 - Procfile
 - nginx
 - Dockerfile
 - prod-config-generator.rb

include:
  - .well-known
  - robots.txt

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - month
    - day
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
