#!/bin/bash

set -euo pipefail

aws_region='us-west-2'
repo='258231756415.dkr.ecr.us-west-2.amazonaws.com/robacarp-com/alfalfa'
env='production'

# Login to AWS ECS Container Store
aws ecr get-login-password --region "$aws_region" \
  | docker login \
    --username AWS \
    --password-stdin \
    '258231756415.dkr.ecr.us-west-2.amazonaws.com'


build_stats () {
  echo '---'
  echo '---'

  echo -n '{ "build_timestamp" : "'
  date "+%Y-%m-%d %H:%M:%S" | tr -d '\n'

  echo -n '", "git_revision" : "'
  git rev-parse HEAD | tr -d '\n'

  echo '"}'
}

function cleanup {
  rm .well-known/BUILD_DETAILS.json
}
trap cleanup EXIT
build_stats > .well-known/BUILD_DETAILS.json

# Build and push the tagged image to your the AWS repository
docker buildx build . \
  --platform linux/amd64,linux/arm64 \
  --push -t "$repo:$env"
