#!/bin/bash

# scripts/build

set -euo pipefail

build_stats () {
  echo '---'
  echo '---'

  echo -n '{ "build_timestamp" : "'
  date "+%Y-%m-%d %H:%M:%S" | tr -d '\n'

  echo -n '", "git_revision" : "'
  git rev-parse HEAD | tr -d '\n'

  echo '"}'
}

function cleanup {
  rm .well-known/BUILD_DETAILS.json
}
trap cleanup EXIT
build_stats > .well-known/BUILD_DETAILS.json

docker build . -t robacarp_com
