#!/bin/bash

aws_region='us-west-2'
cluster='robacarp-com-alfalfa'
service='production-alfalfa-robacarp-com'
minimum_percent_stable=50
maximum_percent_stable=200

set -euo pipefail

aws ecs update-service \
  --region "$aws_region"\
  --cluster "$cluster" \
  --service "$service" \
  --force-new-deployment \
  --deployment-configuration "maximumPercent=$maximum_percent_stable,minimumHealthyPercent=$minimum_percent_stable"
